### PR TITLE
create provided custom dir for keys if none

### LINKED ISSUE #911: Directory for --keys-path is not created
`SecretStore::new` vs `SecretStore::new_in` (the latter is used in `parity/main.rs`)
If the directory doesn't exist keys are not imported and RPC returns `InternalErrors`.

It affects custom `keys-path` but most probably default one also.

### PR DESCRIPTION
**Pull request by NikVolf**
fixes #911 

bug was introduced because `create_dir_all` was called nowhere and tests where using pre-created directory. 

`SecretStore::new` which was actually creating directory for the keys was not used in the current code, since default value was provided via docopt config

### CODE REVIEW

**Comment by arkpar** [comment]
Does it also fix #902?

**Comment by tomusdrw** [comment]
Actually `AccountService::new()` and `SecretStore::new` are not used anywhere - I would remove them.

**Comment by NikVolf** [comment]
Yeah, i'm trying to figure out how it was possible with the default one

**Comment by NikVolf** [comment]
this is of course ok, so must be some permission issue somewhere

```
$ cargo run -- --rpc --pruning fast
```

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"personal_newAccount","params":["123"],"id":1}' http://localhost:8545

{"jsonrpc":"2.0","result":"0x982c38802627b3d3e9859f0bf19e34f9139a7a7f","id":1}

```

**Comment by tomusdrw** [comment]
I think default was also not working because those `SecretStore::new` was never used in current code. Maybe it was used some time ago (or in tests) and this is why we all had `~/.parity/keys`.

For new installations it wasn't created and I think this is why #902 happened.

**Comment by NikVolf** [comment]
yeah, this is possible
both issues should be fixed if that is true

**Pull request merged**
