### PR TITLE
Rustfmt

### PR DESCRIPTION
**Pull request by tomusdrw**
Just to discuss if you like it or not.

### CODE REVIEW

**Comment by debris** [comment]
LGTM

**Comment by arkpar** [comment]
Code looks more readable in general. There are some cases where too many new lines are introduced, e.g.
https://github.com/ethcore/parity/pull/410/files#diff-78fb080adb3a09d3dcbf1af5039d4a55R133
Try enabling `single_line_if_else`

**Comment by tomusdrw** [comment]
@arkpar TBH I would rather see this `if/else` outside of the actual list of parameters like so:
```rust
let sign = match pre > post {
  true => "-",
  false => "+"
};
```
or a function or a macro. IMO it will look equally bad with `single_line_if_else`.

**Comment by arkpar** [comment]
still, I'd prefer
```rust
let sign = if pre > post { "-" } else { "+" };
```
over
```rust
let sign = if pre > post {
    "-"
} else {
    "+"
};
```

**Comment by gavofyork** [comment]
agree with arkadiy - 5 lines for a trivial ternary is no good.

**Comment by NikVolf** [comment]
closing for now, let's reopen when everybody ready to discuss it

**Pull request closed without merging**
