### PR TITLE
Update /api/* to point to :8080/api/* (first generation interface)

### PR DESCRIPTION
**Pull request by jacogr**
- hardcoded paths to 8080 from 8180 for /api/{ping,content,apps} until dapps infrastructure is sorted
- /pai/ping ported to /, no CORS available for former
- load all dapps from :8080 at /ui/dapp.html, i.e. non-WS RPC API
- adds the missing styles.css file for Parity (Rust tests + server needs this for 404s, etc)
- TODO: /api/apps is not supported, no CORS - to be addressed on Rust side
- NOTE: Only to be merged into js when we are ready to go and the Rust side is merged

Depends on https://github.com/ethcore/parity/pull/2220 to be merged into https://github.com/ethcore/parity/pull/2607

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0a3aca60cabf893aa44013b4acb7b4295c12657
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0a3aca60cabf893aa44013b4acb7b4295c12657
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by jacogr** [comment]
Needed for https://github.com/ethcore/parity/issues/2155

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0a3aca60cabf893aa44013b4acb7b4295c12657
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0a3aca60cabf893aa44013b4acb7b4295c12657
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0a3aca60cabf893aa44013b4acb7b4295c12657
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0a3aca60cabf893aa44013b4acb7b4295c12657
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
