### PR TITLE
Install trigger for DAO-rescue soft-fork.

### PR DESCRIPTION
**Pull request by gavofyork**
Soft-fork should only be primed to trigger if the gas-limit of
block #1760000 is at most 4,000,000.

To accomplish this we pass in the gas limit of that block to
EnvInfo so it can inform Schedule. This gets marshalled through
`OpenBlock`/`ClosedBlock` and the `enact` functions much like
`last_hashes`. `block.rs`'s `env_info()` takes care to ensure
that if the current block happens to be #1760000, then we
populate with the current `gas_limit`.

This is a pretty awful altertation to the codebase. However, is has one huge mitigating factor:

**We can revert it after block #1760000.**

### CODE REVIEW

**Comment by debris** [comment]
tests failing

**Comment by taoeffect** [comment]
Wait, what is going on?

Please tell me you are not unilaterally installing a SF into Parity without any EIP and zero calls for public discussion.

Because that would be dumb. Very dumb. I'm already [having to field tweets like this](https://twitter.com/nikcub/status/744425787202277377) and seeing [tweets like this](https://twitter.com/octal/status/744400958440931328). Please don't embarrass us more.

**Comment by gavofyork** [comment]
The soft fork is already in. This PR ensures it only activates if there is consensus among the Ethereum community by requiring it to trigger only if the majority form a consensus around it.

If you want to run Parity and vote against the soft-fork which prevents ETH from being drained from broken DAO contracts (i.e. you wish to help the attacker), run with `--assist-dao-attack`. If you would prefer to stick to the original Homestead Yellow Paper spec, even if the rest of the network goes with the soft-fork, run with `--dogmatic`.

**Comment by taoeffect** [comment]
@gavofyork, like many, I bought into Ethereum because of the message that you and others were selling.

Here you are giving a lecture where you describe Ethereum as a "system that cannot care":

https://www.youtube.com/watch?v=2TXk-VczNL0

And I was at Cryptoeconomicon where you gave a similar lecture pushing the same message.

Now that this system suddenly inconveniences you, you decide to do the exact opposite and change the rules so that things work out in your favor?

This is unacceptable. What do you say to those of us who supported you and Ethereum based on the message you were only just recently pushing?

**Comment by taoeffect** [comment]
Let me be clear: blatant hypocrisy is bad. Blatant hypocrisy involving money is fraud.

**Comment by gavofyork** [comment]
Pease do not abuse PR threads for non-code-related matters. If you want to debate the finer points of consensus, pick a time when I'm less busy and have more beer.

**Pull request merged**
