### PR TITLE
Make miner::TransactionQueue a private interface

### PR DESCRIPTION
**Pull request by nipunn1313**
Noticed while investigating TransactionQueue that it is only used within the miner, so made it into a private interface.

### CODE REVIEW

**Comment by keorn** [comment]
Please fix the [doc tests](https://travis-ci.org/ethcore/parity/jobs/147934671).

**Comment by tomusdrw** [comment]
Hmm, I think this test was actually the reason to have public `TransactionQueue`, it also enforces that all methods are documented. We can convert this to regular test though.

**Comment by nipunn1313** [comment]
Do you think that's worth doing. It seems like given this documentation concern + doctest, it might be nicer to just leave it as public. If you think it's worth converting, I can take care of it.

**Comment by keorn** [comment]
👍 Up to you, close it if you think the other solution is less nice.

**Comment by nipunn1313** [comment]
I'd rather leave it to maintain the documentation

**Pull request closed without merging**
