### PR TITLE
ui compilation feature

### PR DESCRIPTION
**Pull request by tomusdrw**
`$ cargo build [--release] --no-default-features`

It will compile parity without Dapps server and without Signer UI (but with Signer - extension will still work)

### CODE REVIEW

**Comment by gavofyork** [comment]
might be worth consider inverting it to `--features ui`

**Comment by gavofyork** [comment]
doesn't seem to have the desired effect - still chokes on the JS script bug.

**Comment by tomusdrw** [comment]
Cause it's a opt-in feature. We can enable that on Travis but it doesn't make much sense, since JS stuff will not be built.

**Comment by gavofyork** [comment]
despite building locally `$ cargo build --features no-ui`

**Pull request merged**
