### PR TITLE
(Proposal) Improving coverage

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by arkpar** [comment]
Can't say I'm happy with having to put an additional attribute for every test.

**Comment by tomusdrw** [comment]
Maybe a script executed on travis before measuring coverage?

czw., 18.02.2016 o 13:34 użytkownik Arkadiy Paronyan <
notifications@github.com> napisał:

> Can't say I'm happy with having to put an additional attribute for every
> test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethcore/parity/pull/455#issuecomment-185700475>.
>
-- 

Z poważaniem,
Tomasz Drwięga

**Comment by NikVolf** [comment]
@tomusdrw 
great idea, will look into that

**Comment by NikVolf** [comment]
ah, @tomusdrw 
line numbers will not match with repository then

**Pull request closed without merging**
