### PR TITLE
Sweep some more panics

### PR DESCRIPTION
**Pull request by rphmeier**

### CODE REVIEW

**Comment by gavofyork** [comment]
gitlab fails, but everything else succeeds? wtf?

**Comment by rphmeier** [comment]
@gavofyork gitlab appears to be checking out my PR based on a master before #2846.

**Comment by gavofyork** [comment]
gitlab still borked?

**Comment by rphmeier** [comment]
unsure, reopened to see if it'll update the merge head. if not, I would say this is 100% safe to merge.

**Pull request merged**
