### PR TITLE
Split journaldb commit into two functions: journal_under and mark_canonical

### PR DESCRIPTION
**Pull request by rphmeier**
simplifies the API a bit and makes it more flexible w.r.t. marking blocks canonical without actually committing anything new.

(names may be subject to change)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 238b4962f0597f9ee98db503924fb2022dd15c85
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by arkpar** [comment]
Looks good to me assuming nothing has actually changed in the commit logic. It's hard to spot differences in the moved code.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 238b4962f0597f9ee98db503924fb2022dd15c85
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 238b4962f0597f9ee98db503924fb2022dd15c85
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 238b4962f0597f9ee98db503924fb2022dd15c85
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 238b4962f0597f9ee98db503924fb2022dd15c85
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by rphmeier** [comment]
I've tried to fix up the commit message that GitCop is complaining about, but it seems like the rebase won't go through cleanly and there are too many commits.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 238b4962f0597f9ee98db503924fb2022dd15c85
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
