### PR TITLE
CI: test coverage (for core)

### PR DESCRIPTION
**Pull request by General-Beck**
https://github.com/ethcore/parity/issues/4445

### CODE REVIEW

**Comment by rphmeier** [comment]
AFAIK `cov.sh` only does coverage for core. What about coverage for UI code?

**Comment by General-Beck** [comment]
@rphmeier do that, then js

**Comment by rphmeier** [comment]
Ok, makes sense.

**Comment by General-Beck** [comment]
@gavofyork need to check some tests. and empower

**Pull request merged**
