### PR TITLE
Refactor VoteCollector

### PR DESCRIPTION
**Pull request by keorn**
Return error on insertion, faster retrieval.
Fancier error handling will be done in another PR.

Goes after #3937

### CODE REVIEW

**Comment by rphmeier** [comment]
Could use a rebase -- looks like there are some redundant commits in there.

**Comment by keorn** [comment]
Diff is fine though.

**Comment by gavofyork** [comment]
tests failing.

**Comment by keorn** [comment]
`miner::price_info::should_get_price_info` is unrelated

**Comment by gavofyork** [comment]
fair enough - should this be in for 1.5?

**Comment by keorn** [comment]
sure, it will be easier to debug than the old `VoteCollector`

**Pull request merged**
