### PR TITLE
registry dapp: user-friendly lookup

### PR DESCRIPTION
**Pull request by derhuerst**
This PR addresses #2191 by replacing the type input by a dropdown menu with the following entries.

- `A` – Ethereum address
- `IMG` – hash of a picture in the blockchain
- `CONTENT` – hash of a data in the blockchain

### CODE REVIEW

**Comment by jacogr** [comment]
Happy as-is. For IMG, @ngotchac has the same requirement and he will look at actually pulling the picture from Parity - we should re-use between the 2 apps. Basically, the way it works -

IMG is a bytes32 value that is registered with the GithubHint contract. Parity can pull down the images (reverse lookup and serve them up), e.g. going to `http://127.0.0.1:8080/<imageHash>/` will serve the actual image.

**Comment by derhuerst** [comment]
@ngotchac Can you give me an example name for which I get a picture that exists?

**Comment by ngotchac** [comment]
@derhuerst I haven't got an example yet, working on it now.

**Comment by derhuerst** [comment]
Tomasz gave me `dd8a116cfbbd69eb0d21c34b8c137c725140ffc5f230e2a53fae9b1037f694df`.

**Pull request merged**
