### PR TITLE
give appveyor some breath

### PR DESCRIPTION
**Pull request by debris**
As described in https://www.appveyor.com/docs/branches. We have the same configuration on travis.

### CODE REVIEW

**Comment by NikVolf** [comment]
@debris 
they are configured already in web configuration tool like this, btw
but this is more valid place i guess

**Comment by debris** [comment]
@NikVolf I think web config does not work if there is appveyor.yml file. That's why all branches are being build even before making a pull request

**Comment by NikVolf** [comment]
@debris i think they are not working now (exactly in this pr) :)

**Comment by debris** [comment]
weird... [docs](http://help.appveyor.com/discussions/questions/2325-building-only-pull-requests-and-master-branch)

**Comment by debris** [comment]
@NikVolf @gavofyork can you check if the webhook is enabled? http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests#comment_33212404

**Comment by NikVolf** [comment]
@gavofyork - i can't access repo settings

**Comment by gavofyork** [comment]
should be done.

**Comment by NikVolf** [comment]
let's give it a try

**Pull request merged**
