### PR TITLE
cross compilation

### PR DESCRIPTION
**Pull request by General-Beck**
this is concept to cross compile

### CODE REVIEW

**Comment by General-Beck** [comment]
this is concept to cross compile

**Comment by General-Beck** [comment]
clabot:check

**Comment by NikVolf** [comment]
perhaps better do build polishing it in some fork to avoid increasing our present build queue?

**Comment by General-Beck** [comment]
I agree, hurry

**Comment by NikVolf** [comment]
https://github.com/ethcore/parity/pull/718
closed 718 that since seems you are going to revamp everything from ground
you can still check commits there for compiling with clang++ instead of g++

**Comment by gavofyork** [comment]
any movement on this? would be good to have CI for ARM now...

**Pull request closed without merging**
