### PR TITLE
fixed compiling with rustc 1.8.0-nightly (57c357d89 2016-02-16)

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by debris** [comment]
one of the issues is related with linking heapsize on latest nightly ( https://github.com/servo/heapsize/issues/43 )

**Comment by NikVolf** [comment]
will reopen to trigger build

**Comment by NikVolf** [comment]
and reopen once more

**Comment by quininer** [comment]
It will be broken in the next day, because clippy... 
You know, libsyntax is completely unstable.

https://gist.github.com/quininer/76c60b20749e2cdc9a75

Need to be merged as soon https://github.com/ethcore/parity/pull/422

**Comment by NikVolf** [comment]
@quininer this error must be that your nightly version is old
`$ multirust update nightly` ?

**Comment by quininer** [comment]
@NikVolf 
This is a compilation of today.
rustc 1.8.0-dev (b54770c24 2016-02-17)

**Comment by NikVolf** [comment]
@quininer 
ah sorry, since we aiming to build on beta
will try to stick  to version 02/16 of nightly

**Pull request closed without merging**
