### PR TITLE
is_zero() and pow() optimisations for uint

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by tomusdrw** [comment]
Any benchmarks?

**Comment by NikVolf** [comment]
@tomusdrw 
nah benches does not compile for me
it's pretty obvious that `/2` is not optimizes to `>>1' here because it's a u256-param

**Comment by tomusdrw** [comment]
Yeah, I know it will be faster, was just curious about the improvement factor.

**Comment by arkpar** [comment]
I've noticed that this function is really critical to some transactions. A few blocks on the main net take considerably longer to import because of all the divisions.

**Comment by rphmeier** [comment]
the travis build ran out of time, but after all tests passed.

this is good to merge

**Pull request merged**
