### PR TITLE
Fixing order of if statements to avoid overflows.

### LINKED ISSUE #1380: arithmetic operation overflow on ARM
I left `Parity/v1.2.0-unstable-69c29fc-20160620/arm-linux-gnu/rustc1.11.0-dev` running but later found out it'd crashed (I guess it must have been close to fully synced at the time). 

Not sure if it's a random crash related to an HDD connected via USB (there are huge amounts of DEBUG messages in the logs relating to DMA) or a real issue. My guess is the world may have stopped due to lots of SD card `syslog` writes which in turn could have starved parity.

```shell
#1747187 4618…f00f      1 blk/s    5 tx/s   0 Mgas/s    1/ 7 peers   #1747190     0+    0 Qed     46 MiB db   11 MiB chain    2 KiB queue   36 KiB sync

thread 'IO Worker #2' panicked at 'arithmetic operation overflow', util/bigint/src/uint.rs:1137
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted
````

Restarting parity works fine again without any corruptions, getting to fully synced again.

### PR DESCRIPTION
**Pull request by tomusdrw**
Fixes #1380

### CODE REVIEW

**Comment by gavofyork** [comment]
best to put in a comment as to why the ordering is as it is - from the basic diff i can't see where the overflow would occur.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b06ec61f62ce62f5be7a33fc988ee65179beabfa
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b06ec61f62ce62f5be7a33fc988ee65179beabfa
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b06ec61f62ce62f5be7a33fc988ee65179beabfa
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
