### PR TITLE
State backend trait and DiskBacked implementation

### PR DESCRIPTION
**Pull request by rphmeier**
This makes `State` generic over a `Backend` which will be used to perform non-cached state queries.

### CODE REVIEW

**Comment by rphmeier** [comment]
(gonna put this on ice for a bit)

**Comment by rphmeier** [comment]
Ok, this PR is extremely ready for review. Ready when you are :)

**Comment by gavofyork** [comment]
will need resolving

**Comment by rphmeier** [comment]
merges resolved

**Comment by rphmeier** [comment]
looks like my editor automatically removed trailing spaces from `gitlab-ci.yml` when I was fixing merge conflicts

**Comment by rphmeier** [comment]
(CI ran out of time while creating the archive, but all tests passed)

**Comment by gavofyork** [comment]
lgtm - @arkpar want to review?

**Comment by rphmeier** [comment]
right, actually I'm not sure exactly where to go on this PR as it's useful for only two of the three possible solutions to the problem described in #2235 (and which we spoke about a bit earlier). To be honest I'm starting to lean towards the one which doesn't require state backends as the same model would also be useful in recovering from a corrupted database or edge cases in a pruning algorithm.

That said, the backend trait is also useful because it can allow us to create composable backends: 
  - a backend which stores some known subset of the state in a database,
  - wrapped in a backend which has a cache for all parts of the state up to X amount of memory, 
  - wrapped in a backend which stores a bloom filter for optimization)
  - which the `State` holds.

So this is probably worth merging, although my initial approach of using the backend to farm out state queries to the network probably doesn't scale.

**Comment by rphmeier** [comment]
might rework this at some point but the architecture appears to have moved on and left my changes behind :(

**Comment by rphmeier** [comment]
I'd like to revive this soonish (probably from scratch) with a HashDB-based backend, a `Recording<HashDB>` backend, and a `StateDB`-based backend

 Motivation: creating verifying TX proofs for PIP.

**Pull request closed without merging**
