### PR TITLE
Additional RPCs for dapps accounts management

### LINKED ISSUE #3771: Don't restrict accounts by default
Since #3627 is in `eth_accounts` returns empty list by default.
It might be wiser to return a full list if no user action (for compatibility) is taken and have a setting in UI to restrict the default list of accounts (could be part of initial setup, like: "Always expose all account for dapps")

### PR DESCRIPTION
**Pull request by tomusdrw**
Closes #3771

By default `eth_accounts` will return all accounts (as it was before), but it's possible to change policy for new dapps to return only specified whitelist of accounts.

Additionally recent dapps are available in RPC to simplify GUI for that.

### CODE REVIEW

**Comment by gavofyork** [comment]
> it's possible to change policy 

policy should be secure by default.

**Comment by tomusdrw** [comment]
Changed the default policy to return empty list as requested. Marking it as `B1-relnotes` since if it somehow gets released without a proper UI it makes all the dapps useless without an additional RPC call.

**Comment by gavofyork** [comment]
right - will leave it here until @jacogr / @ngotchac make such a UI :-)

**Comment by jacogr** [comment]
@gavofyork & @tomusdrw - UI in progress. 

First round will only be to set the default accounts (available to all dapps) until we have a better way of determining the appids. (Currently it would be the contentHash, which means that each update will force the user to go re-auth their dapps.)

**Comment by tomusdrw** [comment]
I would rather merge this PR if possible even before the UI - it's still an improvement over what we have in master (it allows you to customize the policy).

**Comment by gavofyork** [comment]
ok - if so then we'll need to switch the default policy :-)

**Pull request merged**
