### PR TITLE
Use fdlimit utility crate from crates.io

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by rphmeier** [comment]
link: https://crates.io/crates/fdlimit

**Comment by NikVolf** [comment]
appveyor fail seems unrelated

**Comment by rphmeier** [comment]
Link to repository/docs on the crates.io page would be appreciated -- where is this code stored now?

**Comment by NikVolf** [comment]
https://github.com/ethcore/fdlimit

thought cargo will put it automatically sorry

**Comment by rphmeier** [comment]
LGTM but maybe it's worth bumping the version on crates.io so we can update the manifest fields before merging

**Pull request merged**
