### PR TITLE
Solidity Compiler in UI

### LINKED ISSUE #2276: Contract deployment should allow us to compile Solidity directly
Instead of copy & paste the ABI and bytecode.

### PR DESCRIPTION
**Pull request by ngotchac**
See it in action here : https://youtu.be/RIZJA6A8Iwk

This PR would close #2276 and #3196 

It introduces a new part of the Application to write Solidity contracts and compile them directly here.
The source code is then saved and can be found in the contract view.

In progress:

- [x] Import from Solidity file
- [x] Export to Solidity file
- [x] Save current code to localstorage with a name
- [x] Load from previously saved files
- [x] Load from given snippets

### CODE REVIEW

**Comment by gavofyork** [comment]
maybe see if you can integrate [browser-solidity](https://ethereum.github.io/browser-solidity/#version=soljson-v0.3.6+commit.3fc68da.js&optimize=true) directly?

**Comment by ngotchac** [comment]
There's a lot going on in browser-solidity, might not be necessary for a first approach. Plus, in this PR, everything is run in a Web Worker, which isn't necessarily the case with browser solidity.

**Comment by jacogr** [comment]
Not sure the ABI, contract, etc should show when there is a compiler error.

parity 2016-11-10 15-42-28

**Comment by ngotchac** [comment]
Right, that's because it's not really an error but a formal verification error... Will improve!

**Comment by jacogr** [comment]
Tests still failing. In addition, not quite sure if you addressed the small UI-related issues I raised in Slack - if still busy, just move it to in-progress, alternatively I'll give it a go again in the morning.

**Comment by ngotchac** [comment]
@jacogr Yep, they should be addressed now

**Comment by gavofyork** [comment]
js-tests failing.

**Comment by gavofyork** [comment]
might need a rebase to `master` - there's something funky going on with tests.

**Comment by gavofyork** [comment]
i'm happy enough with the functionality. one of the JS guys should do a proper review though.

**Comment by TbLtzk** [comment]
Awesome! I'd really love to try it. I've seen it's been merged to master, but I don't see it in any release notes. Is it released, or what is the targeted release version?

**Pull request merged**
