### PR TITLE
New default frontier registry

### PR DESCRIPTION
**Pull request by gavofyork**
@arkpar needs to go into all new releases.

### CODE REVIEW

**Comment by gavofyork** [comment]
@jacogr please check it works fine for you. no n eed to recompile - just run with `--chain=ethcore/res/ethereum/frontier.json` once you've pulled.

**Comment by jacogr** [comment]
@gavofyork Works fine with https://github.com/ethcore/parity/pull/4734 activated. Registration & DataChanged events show up as they should.

**Comment by gavofyork** [comment]
cool - in progress as there's a minor rename for Homestead/Frontier coming, too

**Comment by gavofyork** [comment]
closed in favour of a single PR: #4734

**Pull request closed without merging**
