### PR TITLE
Port a couple more RPC APIs to the new auto args

### PR DESCRIPTION
**Pull request by rphmeier**

### CODE REVIEW

**Comment by gavofyork** [comment]
why isn't travis being triggered?

**Comment by rphmeier** [comment]
triggered now.

**Comment by gavofyork** [comment]
oh dear... there's an async RPC now...

**Comment by rphmeier** [comment]
auto args needs to support async (and soon duplex) functions anyway, i'll get it into this PR but can't say exactly when.

**Comment by rphmeier** [comment]
`auto_args` now supports async.

**Comment by rphmeier** [comment]
Looks like this is broken under Rust 1.10.0, due to some improvements to the macro system. Unfortunately, our build is also broken on Windows with 1.12.0. I'll see if I can fiddle with the macros to be backwards compatible.

**Comment by rphmeier** [comment]
on ice until #2423 is resolvable. Turns out 1.12.0 actually made token trees useful and my changes can't be trivially backported.

**Comment by rphmeier** [comment]
(wait for the builds on `a4c9cc6` before merging )

**Pull request merged**
