### PR TITLE
Delete values immediately from DB overlay

### PR DESCRIPTION
**Pull request by arkpar**
About 20% block import speed increase

### CODE REVIEW

**Comment by rphmeier** [comment]
This doesn't add entries of the form (key, -1) like `remove` did when there is no entry for the key

**Comment by gavofyork** [comment]
tests shouldn't be passing; this needs fixing and a test to ensure it's caught.

**Comment by arkpar** [comment]
`OverlayRecentDB` does not keep deleted key-values in memory. All calls to remove were followed by purge. This logic did not change with this PR

**Comment by arkpar** [comment]
This is a pruning overlay for the journaled states, not to be confused with transaction overlay.

**Comment by gavofyork** [comment]
ok, however, the function name should change (since it's not strictly equivalent to `remove` + `purge`), the documentation should be made abundantly clear that it has subtly different semantics (since this could very easily introduce very difficult to detect bugs if a later accidental replacement were to happen that depended on `remove_and_purge` + `insert` giving a 0 ref-count) and it should be demonstrated at the call site that the refs is always > 0.

there should also be an assertion to the same effect in the function.

**Comment by arkpar** [comment]
How is it not equivalent? The function does what the name says, removes a reference count and purges it if it reaches zero or negative.
```
remove();
purge();
insert();
```
is equivalent to 
```
remove_and_purge();
insert();
```
for a particular key of course

**Comment by gavofyork** [comment]
If the key is not in the DB at the beginning, the semantics are different.

- `remove` will insert a key of refs -1 (L238);
- `purge` will leave it in there (L119);
- `insert` will increase it back to *0*.

whereas:

- `remove_and_purge` will do nothing;
- `insert` will insert with a reference count of *1*.

**Comment by arkpar** [comment]
I see, will change `remove_and_purge` to match `purge` behaviour and add a test

**Pull request merged**
