### PR TITLE
fixed #1889, .DS_Store is no longer treated as key file

### LINKED ISSUE #1889: Parity is finding .ds_store when looking for keys in either the ethereum directory or the parity dir
``` 
Kens-MacBook-Pro:MacOS` KenKappler$ parity
2016-08-09 12:28:19 Starting Parity/v1.3.0-unstable-b370867-20160729/x86_64-macos/rustc1.10.0
2016-08-09 12:28:19 Using state DB journalling strategy fast
2016-08-09 12:28:19 Import geth accounts failed. Invalid key file: "/Users/KenKappler/Library/Ethereum/keystore/.DS_Store": "expected value" at line 1 column 1
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidKeyFile("\"/Users/KenKappler/.parity/keys/.DS_Store\": \"expected value\" at line 1 column 1")', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

`rm` ing the offending files fixes this.

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by arkpar** [comment]
Wouldn't it be better to only open .json files?

**Comment by debris** [comment]
key file name does not contain `.json` suffix

**Comment by arkpar** [comment]
Or ignore hidden files at least. It's the same story with `thumbs.db` on windows

**Comment by tomusdrw** [comment]
Why do we panic instead of just displaying a warning that key file couldn't have been loaded?

**Comment by debris** [comment]
> Why do we panic instead of just displaying a warning that key file couldn't have been loaded?

Technically it's not a panic, but quick exit. We assume that our keys must be valid. We display warnings only if geth keys cannot be imported.

**Comment by gavofyork** [comment]
I'm in favour of displaying a warning but not panicking outright when a file in our keys directory cannot be properly loaded as a key.

**Comment by arkpar** [comment]
does not build

**Pull request merged**
