### PR TITLE
Remove 127.0.0.1 references

### PR DESCRIPTION
**Pull request by jacogr**
Partly addresses https://github.com/ethcore/parity/issues/3301

### CODE REVIEW

**Comment by jacogr** [comment]
To be supplemented with a new dappsInterface RPC call to retrieve the full network path from Parity. (To update dappsUrl call in API layer once available)

**Comment by jacogr** [comment]
Moved to in progress so we can have one PR that fixes the full issue in one go.

**Comment by gavofyork** [comment]
looks like work is being continued in #3311.

**Comment by gavofyork** [comment]
will merge this and let work continue under #3311.

**Pull request merged**
