### PR TITLE
Propagations & local transactions tracking

### LINKED ISSUE #2627: Don't clear propagated transactions list on every block

### LINKED ISSUE #2929: Additional tracking and RPCs for submitted transactions
All locally submitted transactions should be tracked through our system; through their journey of dropping, replacement, peer propagation (i.e. which peers have been sent which transactions), pending status in mining blocks and eventual mined status.

This information should be made available over RPC and eventually in the UI so users can figure out what's going on with their tx if it seems like it's not being mined.

### PR DESCRIPTION
**Pull request by tomusdrw**
1. Keeps track of pending transactions propagations
2. Maintains an additional list of local transactions
3. Simple GUI to display transaction queue content and local transactions with possibility of re-submission.
4. Identifies local transactions coming from network correctly (by checking accounts list)

Closes #2929
Closes #2627

### CODE REVIEW

**Comment by tomusdrw** [comment]
Would love some help with the UI (I don't really know how to re-use stuff from other dapps (or how much I can/should re-use in general))
I tried to keep it non-styled for now so that it will be easy to make it properly:
screenshot from 2016-11-17 13 43 41

**Comment by gavofyork** [comment]
looks awesome

**Comment by tomusdrw** [comment]
Spoke with @jacogr and the app will be somehow integrated into main UI later.

**Comment by jacogr** [comment]
One word: YES.

**Comment by gavofyork** [comment]
how can you access the UI for this?

**Pull request merged**
