### PR TITLE
Snapshot sync and block gap info in `eth_syncing`

### LINKED ISSUE #2939: Snapshot sync info over RPC
As well as ancient block downloading status.

With @jacogr

### PR DESCRIPTION
**Pull request by rphmeier**
Closes #2939.

Adds fields to sync info structure returned from `eth_syncing`.
These fields are null when irrelevant.
`blockGap`: array of "first", "last", such that `[first, last)` are all missing from the chain.
`warpChunksAmount`: total amount of snapshot chunks.
`warpChunksProcessed` amount of snapshot chunks processed.

@jacogr All yours!

### CODE REVIEW

**Comment by jacogr** [comment]
Just a basic question - in light of this https://github.com/ethcore/parity/issues/2969 do we really want to extend the standard method?

**Comment by gavofyork** [comment]
@rphmeier can't build (a couple of warnings by the looks of it)

**Comment by gavofyork** [comment]
@jacogr yeah it's fine - we can do it in one big batch.

**Comment by rphmeier** [comment]
@gavofyork Yeah, just a test I forgot to update. I'll add serialization tests for the new fields as well.

**Comment by rphmeier** [comment]
@tomusdrw will the new object format break the old UI?

**Comment by gavofyork** [comment]
old UI? i don't think there's any of that left, is there?

**Comment by tomusdrw** [comment]
Yes, old UI is gone (maybe just chrome extension left), but we were never relying on that method anyway.

Since the change is additive it shouldn't also break any web3-based dapps (i.e. Mist)

**Comment by rphmeier** [comment]
The Old UI will still exist in the 1.3.x series. I'd heard it was broken by previous additive changes to RPC, just keeping an eye out. Are we officially taking the position that the old UI is completely unsupported?

**Comment by gavofyork** [comment]
that is right.

**Comment by gavofyork** [comment]
travis passing, so will assuming is good.

**Pull request merged**
