### PR TITLE
Cleaning up polluted namespaces

### PR DESCRIPTION
**Pull request by tomusdrw**
Closes: #2969 

Summary of changes:
1. `ethcore_*` -> `parity_*`
1. `parity_hashContent` moved to `ethcore_set` (unsafe method)
1. `personal_*` -> `parity_*` (except for methods present in Geth: `listAccounts,newAccount,unlockAccount,signAndSendTransaction...`)
1. Separate namespace for Trusted Signer `signer_` (`confirmRequest, rejectRequest, requestsToConfirm...`)
1. Exposing `personal` over IPC (Mist compatibility)
1. Splitting `EthSigning` - exposing methods only when correct CLI flags are supplied.

Missing:
- [x] JSApi updates
- [ ] ~~Signer extension update - signer now deprecated; all RPC portions can be entirely removed and it should only do the proxy configuration going forward.~~ (will leave for another PR)
- [x] Disable `personal_` RPCs (except when running with `--geth` and over IPC)
- [x] Move any JS over to using `parity_` RPCs instead of `personal_`
- [ ] ~~Move `parity_hashContent` back to being part of `parity` RPCs.~~ (worked around for now. will reconsider.)

### CODE REVIEW

**Comment by jacogr** [comment]
Tracking comment for the JSAPI & UI fixes -

- [ ] Move `ethcore.*` to `parity.*`
  - [ ] api
  - [ ] ui
- [ ] Move affected `personal.*` to `parity.*`
  - [ ] api
  - [ ] ui
- [ ] Add signer namespace
  - [ ] api
  - [ ] ui

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 43b500024b482f103c1b78a51baa3ce6131a7b01
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
