### PR TITLE
Notify user on transaction received

### LINKED ISSUE #2556: Notify users when transaction arrives for any of their accounts

### PR DESCRIPTION
**Pull request by ngotchac**
Closes #2556 until we have a pub/sub mechanism.

Browser notifications will be created whenever we detect an increase in an account value (in ETH or any other registered token). On click, the user is taken to the account page.
This might not work if the account receive `n eth` while sending `n eth` in the same block.
A pub/sub mechanism would be better, but isn't available atm.

### CODE REVIEW

**Comment by jacogr** [comment]
Merge in master for gitlab builds.

**Comment by jacogr** [comment]
Not 100% convinced of this UX -

monosnap 2016-12-10 20-13-44

Seems to work however. Closes way too quickly to even try to interact with it and click.

**Comment by ngotchac** [comment]
This is the default Chrome behavior with notifications. We cannot get away without it.

The timeout is set to 5sec. Could increase it. 10 ? 20 ?

**Comment by jacogr** [comment]
20s is probably a bit long, but ok as a start, easy enough to adjust downwards.

**Pull request merged**
