### PR TITLE
Make JS lint & test run on Travis

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/ethcore/parity/issues/2777

A tiny bit of a jiggle to get multiple languages supported, especially if the 2nd is Node - but the version is now correct and the linting/tests run on Travis. It can no doubt be optimised, but I have a day down on this and it does what it says on the tin.

As for the Travis failure, the js stuff runs and passes, it fails on this -

```
   Updating git repository `https://github.com/ethcore/hyper`
error: failed to load source for a dependency on `hyper`
Caused by:
  Unable to update https://github.com/ethcore/hyper#9e346c1d
Caused by:
  failed to fetch into /home/travis/.cargo/git/db/hyper-03790fdbcffbe388
To learn more, run the command again with --verbose.
```

### CODE REVIEW

**Comment by gavofyork** [comment]
is travis meant to pass?

**Comment by jacogr** [comment]
Yes. Meant to pass. I have no idea why this happens -

```
+cargo test -p rlp -p ethash -p ethcore -p ethcore-bigint -p ethcore-dapps -p ethcore-rpc -p ethcore-signer -p ethcore-util -p ethcore-network -p ethcore-io -p ethkey -p ethstore -p ethsync -p ethcore-ipc -p ethcore-ipc-tests -p ethcore-ipc-nano -p parity --no-run
    Updating git repository `https://github.com/ethcore/hyper`
error: failed to load source for a dependency on `hyper`
Caused by:
  Unable to update https://github.com/ethcore/hyper#9e346c1d
Caused by:
  failed to fetch into /home/travis/.cargo/git/db/hyper-03790fdbcffbe388
To learn more, run the command again with --verbose.
+exit 101
The command "if [ "$RUN_COVERAGE" = "true" ]; then ./scripts/cov.sh "$KCOV_CMD"; fi" exited with 101.
```

Have not touched that. Will re-look at it again as soon as I have a gap, just need to get through proper end-to-end UI testing for release first.

**Comment by gavofyork** [comment]
to be honest we'll remove travis as soon as gitlab is integrated for all major platform/test combinations.

**Comment by jacogr** [comment]
Agreed. The only reason why this was done was because of the issues we've had with GitLab stability - had 2 merges during extended GitLab downtime (testing failures in both), that started failing builds when it came back up and put us in fire-fighting mode.

In addition, the structure is much more extensive for the JS side of things on GitLab (does much more, this is very basic) so this is just a short-term failsafe so we don't end up with failing master yet again.

**Pull request merged**
