### PR TITLE
Reserved peers rpc API

### PR DESCRIPTION
**Pull request by rphmeier**
Appears to work, but can't test whether no reserved nodes will be accepted without deploying to one of our nodes and testing for a few hours.

Also need some reliable nodes to test as reserved nodes -- I've been using the bootnodes, but only 1 of them ever reliably connects.

Does not include the suggested "passive" API, as that is more involved with the sync code and is better saved for a later PR.

### CODE REVIEW

**Comment by rphmeier** [comment]
A current fallback: stopping and starting the network will erase reserved peers not specified at startup and non-reserved peer mode.

**Comment by rphmeier** [comment]
(testing on pi.parity.io shows that this works as expected)

**Comment by gavofyork** [comment]
could you file the "shortcoming" as an issue?

**Comment by rphmeier** [comment]
@gavofyork There is a tracking issue open here: https://github.com/ethcore/parity/issues/1336

**Pull request merged**
