### PR TITLE
Passwords are valid by default

### LINKED ISSUE #4059: Creating account with empty phrase does not work as expected
(To check)

From Slack -

peter [7:01 PM]  
cant import account with empty recovery phrase through UI, will that be changed? if not I will change the account in the dev chain.

jacogr [8:42 PM]  
Let me check, I’m sure we are supposed to allow empty phrases now.`

It is definitely supposed to allow it according to the what is intended by the code since we removed all length checks, there may be a bug with a completely empty phrase, will investigate.

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes  #4059

By default, passwords are valid because empty and equivalent

### CODE REVIEW

**Comment by jacogr** [comment]
The original issue refers to the recovery phrase - does the password solve that issue?

**Comment by ngotchac** [comment]
Ah yep, sorry.

**Comment by jacogr** [comment]
You did fix bug, just wan't convinced it was the linked bug :)

**Comment by ngotchac** [comment]
Should be fixed now

**Pull request merged**
