### PR TITLE
small cleanup

### PR DESCRIPTION
**Pull request by debris**
a few small changes:

- removed usages of hardcoded uncles position

  ```diff 
-for u in Rlp::new(bytes).at(2).iter().map(|rlp| rlp.as_val::<Header>())
+for u in &BlockView::new(&bytes).uncles()

-let uncles_count = Rlp::new(bytes).at(2).item_count();
+let uncles_count = BlockView::new(bytes).uncles_count();
  ```

- simplified engine interface, removed unused params
  ```diff
-fn verify_block_basic(&self, header: &Header, _block: Option<&[u8]>)
+fn verify_header_basic(&self, header: &Header)

-fn verify_block_unordered(&self, header: &Header, _block: Option<&[u8]>)
+fn verify_header_unordered(&self, header: &Header)

-fn verify_block_family(&self, header: &Header, parent: &Header, _block: Option<&[u8]>)
+fn verify_header_family(&self, header: &Header, parent: &Header)
  ```

- simplified one of the methods in `verification.rs`
  ```diff
-fn verify_header(header: &Header, engine: &Engine) -> Result<(), Error>
+fn verify_header(header: &Header, params: &CommonParams) -> Result<(), Error>
  ```

### CODE REVIEW

**Comment by gavofyork** [comment]
> simplified engine interface, removed unused params

this isn't a shrink-fit API: that those parameters happen to be unused for the Ethash PoW engine is not good reason to remove from this API designed to be the main point for further engine development.

in fact a likely PoS engine would make use of one of more of these parameters.

**Comment by debris** [comment]
> this isn't a shrink-fit API: that those parameters happen to be unused for the Ethash PoW engine is not good reason to remove from this API designed to be the main point for further engine development.

imo, it would be just better to avoid interfaces with optional input params. The usage of such methods is not always clear.

> in fact a likely PoS engine would make use of one of more of these parameters.

I suggest adding additional method(s) to the engine interface then. Without utilizing optional input params.

 eg.

```
fn verify_XXX(block: &[u8])
```.

**Comment by gavofyork** [comment]
> imo, it would be just better to avoid interfaces with optional input params. The usage of such methods is not always clear.

fair enough; if the `Option` can be removed, it should be.

> I suggest adding additional method(s) to the engine interface then.

there are already enough functions for verification given the stages our verifier has. better to work out which existing functions can reasonably get block information and supply them with it. since we don't yet know how future consensus mechanisms will use this API, better to define it in (comprehensive) terms of what is available to give, not in (minimalist) terms of what we believe we may need.

**Comment by NikVolf** [comment]
Let's close while no activity here

**Pull request closed without merging**
