### PR TITLE
memorydb UB patch and minor cleanup

### PR DESCRIPTION
**Pull request by rphmeier**
please review all the unsafe code introduced here very carefully. very subtle aliasing bugs could be introduced and lead to other UB

### CODE REVIEW

**Comment by gavofyork** [comment]
lgtm

**Comment by rphmeier** [comment]
this is a solution but probably not a perfect one -- Ideally I would restructure like so:
  - do away with denote entirely 
  - overhaul the `HashDB` interface to return an enum around either a slice or `Ref<[u8]>`
  - have `JournalDB` implementations manage a RefCell-wrapped cache which is rolled into the overlay before every insert/delete operation

i am hesitant to introduce new unsafe code here because this is one of the more user-facing portions of the codebase. although this is really unlikely, this _could_ open up some miraculously obscure attack vector which could be triggered by manipulating contract storage very particularly.

**Comment by gavofyork** [comment]
travis failed.

**Comment by rphmeier** [comment]
(the `denote` mechanism is fundamentally incompatible with multithreading as it stands)
i am preparing a mutex-based implementation which will solve the issue more cleanly

**Comment by rphmeier** [comment]
this requires a significant amount of rearchitecture. closing until that is finished

**Pull request closed without merging**
