### PR TITLE
Limit sync reorganization to 20 blocks

### PR DESCRIPTION
**Pull request by arkpar**

### CODE REVIEW

**Comment by rphmeier** [comment]
What's the motivation for this change?

**Comment by arkpar** [comment]
Prevents us from searching for common block indefinitely. 
This was lost somehow during refactoring.

**Comment by rphmeier** [comment]
It does feel a bit fragile though. Limiting reorganization amount is supposed to be managed by pruning history, so a hard limit at 20 feels overly restrictive. Can't the sync service just check if the newly-given block is actually useful?

**Comment by arkpar** [comment]
PV63 does not provide means to check if the `NewHashes` hash is useful. We need to download the  header first and then find what chain it belongs to

**Pull request merged**
