### PR TITLE
Fix signer token updates

### PR DESCRIPTION
**Pull request by jacogr**
- when token is initially set to "initial" set correct state
- fix broken signer paste dialog
- fix case where status update promise don't return (signer window hanging)

### CODE REVIEW

**Comment by jacogr** [comment]
@ngotchac Please check.

**Comment by jacogr** [comment]
Fixes https://github.com/ethcore/parity/issues/3305
Fixes https://github.com/ethcore/parity/issues/3306

**Comment by gavofyork** [comment]
signer tests failing now. @tomusdrw ?

**Comment by jacogr** [comment]
Tests passing after retry, PR fix for tests available.

**Pull request merged**
