### PR TITLE
update Morden registry address - beta

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by rphmeier** [comment]
Has it fixed the corresponding test which was failing in master?

**Comment by NikVolf** [comment]
@rphmeier i believe so, this is the commit from the merged pr

**Comment by rphmeier** [comment]
I think the issue was that that PR accidentally changed the address without updating the test

**Comment by NikVolf** [comment]
let @jacogr review that
because i have no idea

**Comment by NikVolf** [comment]
@jacogr ?

**Comment by jacogr** [comment]
Ok, as rightly said, I didn't update the test on master - Arkardiy did so, I couldn't cherry-pick that patch to apply to Beta since it was part of other fixes. As such this will cause failures until the corresponding test is also updated.

However, I really don' think the test should test for the specific address, rather just that it is an address and the json is not empty.

Having said that. I am still not convinced this should be backported - we will only use the registry as part of the new UI as of now it is there, but not used by anybody apart from us. The old version is fine for 1.3.x, the changes done to the contract doesn't affect operation.

**Comment by NikVolf** [comment]
@jacogr so just delete test then in beta?

**Comment by jacogr** [comment]
Test updated for master - when passed and deemed sufficient, would also merge that into this PR - https://github.com/ethcore/parity/pull/2476 (fixing the test hopefully for the long term)

**Pull request closed without merging**
