### PR TITLE
Even more snapshot validity checks

### PR DESCRIPTION
**Pull request by rphmeier**
Future work:
  - restart sync on bad ancient block.
  - sync service should find canonical block hashes which the service will use for additional verification.

### CODE REVIEW

**Comment by arkpar** [comment]
Additional changes to ethash DAG caching are required. Latest DAG should be preserved and never evicted. Otherwise we'll have significant block delays when importing new blocks with background download because the latest gets evicted by ancient checks.

**Comment by rphmeier** [comment]
Good point. I'll see what can be done about it. In the case of manually restarted sync we will want to clear everything though; a simple rule like "always keep the DAG with the latest era" probably won't be enough.

**Comment by rphmeier** [comment]
@gavofyork also suggested verifying total difficulty of the best block compared to what peers on the network say about it. If possible, this data should be collected before beginning the restoration of the snapshot.

**Comment by gavofyork** [comment]
some tests would be good at some point.

**Pull request merged**
