### PR TITLE
Coloured, padding logging.

### LINKED ISSUE #1131: Pad numbers in Informant
```
[ #999569 21e3…48d2 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/2 peers, #999569, 0+0 queued ···// mem: 0 bytes db, 203 KiB chain, 2 KiB queue, 9 KiB sync ]
[ #999571 a453…64fb ]---[ 0 blk/s | 0 tx/s | 10079 gas/s  //··· 0/2 peers, #999571, 0+0 queued ···// mem: 0 bytes db, 346 KiB chain, 2 KiB queue, 9 KiB sync ]
[ #999572 daef…8142 ]---[ 0 blk/s | 0 tx/s | 0 gas/s  //··· 0/2 peers, #999572, 0+0 queued ···// mem: 0 bytes db, 191 KiB chain, 2 KiB queue, 9 KiB sync ]
```
turn it into:
```
[ #999569 21e3…48d2 ]---[  0 blk/s |  0 tx/s |     0 gas/s  //··· 0/2 peers, #999569, 0+0 queued ···// mem: 0 bytes db, 203 KiB chain, 2 KiB queue, 9 KiB sync ]
[ #999571 a453…64fb ]---[  0 blk/s |  0 tx/s | 10079 gas/s  //··· 0/2 peers, #999571, 0+0 queued ···// mem: 0 bytes db, 346 KiB chain, 2 KiB queue, 9 KiB sync ]
[ #999572 daef…8142 ]---[  0 blk/s |  0 tx/s |     0 gas/s  //··· 0/2 peers, #999572, 0+0 queued ···// mem: 0 bytes db, 191 KiB chain, 2 KiB queue, 9 KiB sync ]
```

to have nice, consistent output.

### PR DESCRIPTION
**Pull request by gavofyork**
Fixes #1131.

### CODE REVIEW

**Comment by debris** [comment]
Can we use something like https://github.com/ogham/rust-ansi-term instead?

**Comment by arkpar** [comment]
does the output still look good when redirected to a file?

**Comment by gavofyork** [comment]
rust-ansi-term does look quite nice. i'll port to that in next PR.

**Comment by gavofyork** [comment]
haven't checked file redirection; i imagine if you cat the file into an xterm it'll look ok ;)

**Comment by arkpar** [comment]
I'd prefer a way to disable colouring (maybe a `--no-colour` option). Navigating a log file in the text editor could be a pain.

**Comment by gavofyork** [comment]
will add a second PR.

**Pull request merged**
