### PR TITLE
Allow operation when no registry is available

### PR DESCRIPTION
**Pull request by jacogr**
- Allows the display of native network balances even when Tokens are not available, Fixes https://github.com/ethcore/parity/issues/2975 (Registry -> TokenReg)
- Remove built-in dapps when no registry is found, Fixes https://github.com/ethcore/parity/issues/2979

### CODE REVIEW

**Comment by ngotchac** [comment]
There seems to be some errors when there is no Registry contract address (`_retrieveTokens Error: -32602: Invalid params` or `Error: -32602: Invalid params(…)` in `ws.js`). I guess some part of the app is not checking if there is actually a registry deployed.

It also seems that my local dApp which doesn't uses the registry isn't displayed/accessible.

**Comment by jacogr** [comment]
Ok, the local dapp should definitely show, that needs to be addressed - only builtins should be removed. 

The intent was not to remove the actual check from all places, just made sure that when they fail, they are ignored. (There are a number of combinations when done properly, no Registry, Registry but no TokenReg, etc.)

**Comment by jacogr** [comment]
As discussed & shown, cannot replicate the dapps issue. Others issues not for this release, could do it straight-after.

**Comment by ngotchac** [comment]
My bad, it is working...

**Pull request merged**
