### PR TITLE
Display QrCode for accounts, addresses & contracts

### PR DESCRIPTION
**Pull request by jacogr**
QrCode verified scannable and returning the correct address via iOS Ethereum wallet.

parity 2017-01-27 14-17-14

### CODE REVIEW

**Comment by ngotchac** [comment]
It looks really unbalanced to me. Can't the tokens still be right bellow the name/address ? Might want to have a smaller QR Code too, with some opacity, that could grow and be opaque on hover, no ? Right now it looks like it's the main info

**Comment by ngotchac** [comment]
Also, don't we want to wait for https://github.com/ethcore/parity/issues/4267 so we can directly embed links to the address ?

**Comment by jacogr** [comment]
Wouldn't make this dependent on #4267 at all, just going to blow up for no reason. Could definately squish down the size a bit and see how the tokens flow.

**Comment by ngotchac** [comment]
@jacogr Ok. And I didn't mean dependant, but maybe just wait for use to support this `web+ethereum:...` pattern and use it there. Not sure if it's what we want for the QR code, but if it is, then changing from plain address to URL might be misleading, no ?

**Comment by jacogr** [comment]
QrCode is there for scanning first and foremost. So I want to scan the address on my iOS app and send it ETH. (And once we have this https://github.com/ethcore/parity/issues/3075 in, we will add it to the signer as well)

**Comment by ngotchac** [comment]
But isn't it the point of scanning ? So that the mobile phone can trigger the right app to send a payment without having to copy-paste ?

**Comment by jacogr** [comment]
Taking this to Slack since I we are missing each other here.

**Comment by ngotchac** [comment]
My bad, misunderstanding... Just waiting on UI changes then

**Comment by jacogr** [comment]
Updated. Ended up not using flex within flex here, sticking to the float right - although there is less floating going on now.

parity 2017-01-27 14-12-26

**Pull request merged**
