### PR TITLE
Add missing 'make' dependency (now required by ring)

### PR DESCRIPTION
**Pull request by rangelife**

### CODE REVIEW

**Comment by gavofyork** [comment]
[clabot:check]

**Comment by jesuscript** [comment]
[clabot:check]

**Comment by jesuscript** [comment]
@rangelife thanks a bunch for your PR. Could you please sign the CLA today if you want this merged. I might have to close this PR and open one myself if you don't as this needs to be fixed asap.

**Comment by rangelife** [comment]
Hi Konstantin

As I work for a corporation my manager needs to approve the licence, and he
won't be back in the office til tomorrow.

If you do close it yourself I'll still proceed to sign the CLA so I can act
more quickly in future.

Thanks

**Comment by jesuscript** [comment]
Fair enough. Closing this in favour of https://github.com/ethcore/parity/pull/3666 . 

Really appreciate you flagging this up. In the future, with a signed CLA we will be able to have your contributions properly credited

**Comment by rangelife** [comment]
clabot:check

**Comment by rangelife** [comment]
presuably the clabot won't stand in my way next time...?

**Comment by jesuscript** [comment]
[clabot:check]

**Comment by rangelife** [comment]
ah :-) forgot the []s, thanks

**Pull request closed without merging**
