### PR TITLE
LES Part 2

### PR DESCRIPTION
**Pull request by rphmeier**
- All request handlers implemented
- Provider implemented for `Client` via `ProvingBlockChainClient` trait (without CHT stuff, see #3458)
- Simple event handlers, constructor
- Request dispatch, although responses will lead to panic for the moment

### CODE REVIEW

**Comment by rphmeier** [comment]
Next PR will contain:
  - CHT for full node (may require DB migration)
  - Response handlers
  - At least part of light sync service

**Comment by rphmeier** [comment]
I swear I used `git mv` when moving the `light` module location...

**Comment by arkpar** [comment]
> Move light module into ethcore crate for IPC codegen
Whys is this needed? Codegen works just fine for `ethsync` crate. Maybe move to `ethsync` instead?

**Comment by rphmeier** [comment]
@arkpar Most of the reason was actually that the implementation of `Provider` for `Client` needed access to a lot of internals which just weren't available outside of the `ethcore` crate.

The `net` primitives are also lower level than the light sync service, although that will involve an instantiation of the `LightProtocol`. I will be writing the sync/serve processes within the `ethsync` crate, but this will be in the next PR.

**Comment by rphmeier** [comment]
Thinking on it a bit more, it should be possible to have `ethcore-light` as its own crate again, with the addition of a `trait StateAt: BlockChainClient { }` and `impl<T: StateAt + ?Sized> Provider for T { ... }` in `ethcore`.

I can add that change to this PR if you'd like.

**Comment by arkpar** [comment]
I'd like to keep `ethcore` crate as light (pun not intended) as possible. It is becoming monstrous already. And introducing dependency on `ethcore-network` does not seem right. I'm fine if it happens in the next PR.

**Comment by rphmeier** [comment]
This is ready for review again.

**Pull request merged**
