### PR TITLE
Graphical gas price selection

### LINKED ISSUE #2142: sending should allow graphical gasPrice selection
- when sending, instead of putting in a price, do it graphically
- curve based on previous values available via eth_gasPriceStatistics
- needs to be intuitive

(Split from https://github.com/ethcore/parity/issues/2114)

### PR DESCRIPTION
**Pull request by ngotchac**
Closes #2142 

The description text might need to be edited...

parity-ui-gas-select

### CODE REVIEW

**Comment by keorn** [comment]
Its not really octile since there are 9 sets. Is y axis is the price for a particular quantile?

**Comment by jacogr** [comment]
It is based on what we get back from `eth_gasPriceStatistics`

**Comment by jacogr** [comment]
Think it is quite close, have a coupld small nigglies I'll plop next to you for. 

Also want @gavofyork 's feedback on this one - he originally asked for it.

**Comment by gavofyork** [comment]
@keorn and i always through you were good at maths! :-P

it's octile:

image

**Comment by gavofyork** [comment]
this is correct, fwiw (most people use sensible gas price, one or two something 10x on that), though we may want to place Y on a log scale and/or remove max/min (first and last elements) from the graph.

**Comment by keorn** [comment]
Does 9 divisions make 8 sets (no, 7)? Not sure where that screenshot is from :P, [here is a source](https://en.oxforddictionaries.com/definition/octile).

**Comment by ngotchac** [comment]
Well, N+1 values makes N sets : [1, 2, 3] makes two sets: [1 ; 2] and [2 ; 3]

**Comment by keorn** [comment]
Yes, but quantiles divide the total population so only the internal divisions are meaningful. So does this mean that the graphic shows the most extreme values as the leftmost and rightmost bars?

**Comment by ngotchac** [comment]
Yes I think so.


So here are 3 different version, based on your comments:

1. Default version
parity-ui-gas-default

2. Log scale
parity-ui-gas-log

3. Sliced (without min and max)
parity-ui-gas-sliced

**Comment by keorn** [comment]
3 looks about right (often 90% of transactions have the same price) and is not very nice. It might be better to have price on the x axis (where you do the sliding) and y axis would show the proportion of transactions you are ahead of.

**Comment by gavofyork** [comment]
the distribution is different to the original screenshot - all the bands are equal so it's rather dysfunctional. the data for the graph are indeed octile points, so the visualisation as bands is a little misleading. that said, 99% of users will not care at all.

**Comment by gavofyork** [comment]
agree with @keorn though.

**Comment by jacogr** [comment]
Moved to in-progress, different APIs for display to be added.

**Comment by ngotchac** [comment]
Current UI : https://youtu.be/0kINeUtmMJ8

**Comment by ngotchac** [comment]
Now using the new `gasPriceHistogram` RPC call : displays the gas price selection from this histogram.

screenshot_2016-10-31_17-49-43

**Comment by keorn** [comment]
As @rphmeier mentioned, might be good to say that these are included transactions. Also more outliers can be cut or more buckets used to make the histogram a bit more interesting, but the range now is usually between reasonable 20 and 50 Gwei.

**Comment by rphmeier** [comment]
(as a test, I submitted a tx yesterday with 15Gwei price. It took 12 hours to mine -- if you're comfortable with typical bank transfer times you might prefer the option to select outside of the range.)

**Comment by ngotchac** [comment]
The value can also be modified from the text input field on the right of the graph.

**Comment by jacogr** [comment]
We are entering the "this dialog is way too high" territory - cut 15% of the graph and combine the 2 paragraphs at the bottom. (It would make sense to do these 0.75em as well, just to fit in with "labelling")

Apart from that, looks almost usable now... We may want to try log scale again as well, just since there are massive jumps with the numbers.

**Comment by ngotchac** [comment]
So this is how it looks like with a log scale (far left is for 111 transactions, the second highest is 4 transactions)

parity-gas-select-log

As for the _legend_ font size, 0.75em is really unreadable to me, so I put it at 0.9

**Comment by keorn** [comment]
imho
Can't this section be made optional (like advanced settings)? Default gas price from median is an alright estimator for most people who do not need to be shown all this complexity. Then you could have 3 steps + optional advanced settings.

**Comment by ngotchac** [comment]
@keorn Yep this is already the case. You have to check `advanced settings` (or equivalent) to access this gas price selector

**Comment by jacogr** [comment]
Lint issues, check GitLab.

**Comment by ngotchac** [comment]
Ok, fixed

**Pull request merged**
