### PR TITLE
Separate crate for transaction_queue and mining.

### PR DESCRIPTION
**Pull request by tomusdrw**
I'm not sure how it should look like. So will be grateful for hints.

### CODE REVIEW

**Comment by tomusdrw** [comment]
Fixes #584

**Comment by gavofyork** [comment]
architecture and code quality look good. have you given it a once over on the morden testnet mining a few blocks?

**Comment by tomusdrw** [comment]
Not yet I'm just running `tx_queue_integration` for couple of days.  Will try in the morning.

**Comment by gavofyork** [comment]
needs merge.

**Comment by tomusdrw** [comment]
Will repoen to merge with master

**Pull request closed without merging**
