### PR TITLE
Determine real-time HTTP connected status

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/ethcore/parity/issues/3330

(Will swap to `parity_ping` once available)

### CODE REVIEW

**Comment by derhuerst** [comment]
Looks good imo. Isn't polling once a second pretty often? We already have another polling mechanism in place (`HTTP HEAD /`), which we might combine with this one.

**Comment by jacogr** [comment]
This is for the HTTP API, nothing to do with the UI at all. isConnected gets handled properly for the WS API (since we get feedback and make a connection, so actually there is a discrepancy between the two transports). 

The UI doesn't use HTTP anywhere, while Dapps don't use the ping nor currently have feedback on the actual node. (As reported in the linked issue)

API call to be replaced with `parity_ping` (once available - and probably backported to beta)

**Comment by jacogr** [comment]
Merged in master for test failures.

**Comment by gavofyork** [comment]
tests still failing.

**Comment by jacogr** [comment]
Ok, looking at it yet again, these are real failures - missed a beat. Moving to in-progress until properly fixed.

**Comment by jacogr** [comment]
Failing tests finally fixed. (Expecting a sequence of mocked calls with polling timeouts in-between is not the best match for consistency)

**Pull request merged**
