### PR TITLE
kcov uses travis_job_id instead of coveralls token

### PR DESCRIPTION
**Pull request by debris**
it should fix coverage reports

### CODE REVIEW

**Comment by NikVolf** [comment]
why there is no CI checks on this one?

**Comment by debris** [comment]
No idea. Looks like travis.org is not working properly again...

**Comment by debris** [comment]
according to https://travis-ci.org/ethcore/parity/requests job was accepted. Don't know why build hasn't started

**Comment by NikVolf** [comment]
"branch not included or excluded" there

**Comment by NikVolf** [comment]
we should have stayed on travis-pro :)

**Pull request merged**
