### PR TITLE
delay bomb for Classic (ECIP-1010)

### PR DESCRIPTION
**Pull request by splix**
This is an implementations for Bomb Delay that is planed for January ETC protocol upgrade (block 3,000,000). It's already implemented in Classic Geth, and these commits are adding compatibility for future fork into Parity as well.

See also:
* ECIP-1010 https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1010.md

PS it also includes unit tests for difficulty calculation, which were in your TODO

### CODE REVIEW

**Comment by splix** [comment]
[clabot:check]

**Comment by gavofyork** [comment]
looks good in general; is there some way to combine `bombPauseTransition` and `bombDiffuseTransition`?

**Comment by gavofyork** [comment]
will also need a rebase.

**Comment by splix** [comment]
rebased

**Comment by splix** [comment]
`bombDiffuseTransition` is a different thing imho. It could be set to some block too some time later when ETC community will decide about _diffusion_, but for now it's just a _pause_.

Also, I've noticed that other parameters are prefixed with eip number, like `eip160_transition`. If that's a standard naming schema, I can rename our options to `ecip1010_pause_transition`, `ecip1010_continue_transition`. Should I do that?

**Comment by gavofyork** [comment]
re: naming - sure.

not sure what went wrong with the rebase but it's now brought in all the changes from the EIP-155/160/161 hardfork PR.

will need to be untangled before sign off.

**Comment by splix** [comment]
Ok, I'm going to rename options and will make a new clean Pull Request

**Comment by splix** [comment]
Resubmitted with #3179

**Pull request closed without merging**
