### PR TITLE
Update deb-build.sh to fix libssl dependency

### PR DESCRIPTION
**Pull request by slyon**

### CODE REVIEW

**Comment by slyon** [comment]
[clabot:check]

**Comment by tomusdrw** [comment]
Doesn't it break compatibility with anything > Debian Jessie? @arkpar ?

**Comment by rphmeier** [comment]
Should be backported to `beta` as well.

**Comment by 5chdn** [comment]
> Doesn't it break compatibility with anything > Debian Jessie?

Yes, we should revert this.

**Pull request merged**
