### PR TITLE
Nicer port in use errors

### PR DESCRIPTION
**Pull request by keorn**

### CODE REVIEW

**Comment by tomusdrw** [comment]
I think I would add something like: `make sure that another instance of Parity or geth is not running or specify different port using: `

**Comment by tomusdrw** [comment]
And would be good if there was a similar message for Signer and Network too :)

**Comment by keorn** [comment]
It is fine to run another Parity instance, it just has to use different resources.

**Comment by tomusdrw** [comment]
Yes, but it suggests to non tech-savvy users what (may have) caused the problem.

**Pull request merged**
