### PR TITLE
Common EngineSigner

### PR DESCRIPTION
**Pull request by keorn**
Reusable `EngineSigner` for signing consensus messages. Goes after #4184.

### CODE REVIEW

**Comment by rphmeier** [comment]
Documentation on all public items would be a plus

**Comment by rphmeier** [comment]
Why not take it a step further and make `EngineSigner` a trait with its current interface? Would serve to decouple `Engine` from implementation details like `AccountProvider` and make it more testable via mocked signers.

**Comment by keorn** [comment]
Its a very simple struct and is tested via multiple `Engine` tests. I dont see much reason for different implementations for now, once we need them it can be easily turned into a trait. imho this is simpler

**Comment by gavofyork** [comment]
need resolving.

**Comment by gavofyork** [comment]
i was also imagining a trait + trait object, but this is a decent first step.

**Pull request merged**
