### PR TITLE
Unsubscribe error on ShapeShift modal close

### PR DESCRIPTION
**Pull request by jacogr**
- allow for double unsubscribe
- tests for subscribe/unsubscribe
- reproduce already-unsubscribed failure

### CODE REVIEW

**Comment by ngotchac** [comment]
Would prefer to keep the `unsubscribe` call in the `onUnmount` as well

**Comment by jacogr** [comment]
Doesn't make sense having it in both places. 

However, going to revisit rather - first need a test that reproduces the error first so can be sure it is fixed whichever way instead of re-visiting at some point. A bit blind here and this may or may not do the trick, which is not acceptable.

**Comment by jacogr** [comment]
@ngotchac As expected, looked in the wrong place. With auto-unsubscribe (which didn't use the proper unsubscribe function, just set the values null) we caught an error when completed and trying again in unmounting the component. Fixed at source.

**Comment by ngotchac** [comment]
Looks good from a code point of view, however cannot really test fully with Shapeshift

**Comment by ngotchac** [comment]
Looks good. Would just get rid of the `console.log` here https://github.com/ethcore/parity/blob/jg-shapeshift-unsubscribe/js/src/modals/Shapeshift/shapeshift.js#L269 (just adds some noise IMO)

**Comment by jacogr** [comment]
Actually find that info quite useful, however that is for another PR since this one has not touched the modal, nor introduced that code - have one open where the modal is addressed, i.e. https://github.com/ethcore/parity/pull/4035

**Pull request merged**
