### PR TITLE
move existing rpc tests into mocked module

### PR DESCRIPTION
**Pull request by rphmeier**
this is in preparation for unit tests which use the actual `BlockChainClient` and `Miner`

### CODE REVIEW

**Comment by NikVolf** [comment]
(just moving sources, i guess) - lgtm

**Comment by rphmeier** [comment]
cc @tomusdrw You mentioned to me that some of the tests have logic -- I skimmed them quickly and none stood out to me in particular. Please let me know if there are any tests which should not be moved to this module.

**Comment by tomusdrw** [comment]
I meant that some of the implementations have some logic (like `eth_syncing` unforunately untested or `eth_sendTransaction` (default values)) but I guess the logic is untested anyway.

I just think that calling them serialization tests might be perceived a bit unfair :) But no strong feelings.

**Comment by rphmeier** [comment]
Ah, I understand. I also think that serialization is probably not the best name, since it isn't really quite right either. Maybe call it "mocked" since everything but the RPC server is being mocked?

**Comment by rphmeier** [comment]
rebased onto latest master

**Pull request merged**
