### PR TITLE
Get bigint on crates.io

### PR DESCRIPTION
**Pull request by rphmeier**
As `ethcore-bigint`

### CODE REVIEW

**Comment by tomusdrw** [comment]
What's the benefit if the code is in a single repo anyway?

**Comment by rphmeier** [comment]
It makes it easier to observe changes -- personally I hate to review a PR which is just a version bump + Cargo.lock hash change.

**Comment by tomusdrw** [comment]
Oh, yeah - I agree. My point is why do we change references to `ethcore-bigint` from `ethcore-bigint = {path = "../util/bigint"}` to `ethcore-bigint = "<crates-version>"`

Right now someone will make a change in `util/bigint` and it will not be used when compiling parity so we won't be even able to figure out that something is broken.

**Comment by arkpar** [comment]
Agree with @tomusdrw. Local references should use relative path.

**Comment by rphmeier** [comment]
my reasoning behind using crates.io version was to ensure that changes actually get propagated to crates.io. if not, the crate might stagnate more than necessary.

but i suppose the relative path is probably better

**Comment by rphmeier** [comment]
Another reason, which only just occurred to me now, is that you can't have local dependencies for published crates.

As we may want to publish an `rlp` and `trie` crate, they will need to reference concrete `crates.io` versions. I think cargo workspaces will smooth this over a bit.

**Comment by rphmeier** [comment]
Travis failure seems spurious, it's very strange. It can't fetch the source for https://github.com/ethcore/hyper for some reason.

**Pull request merged**
