### PR TITLE
Personal split

### PR DESCRIPTION
**Pull request by jacogr**
Split personal_* RPC into safe & unsafe parts. End-result is that the safe parts are available to dapps as well, which includes

- `personal_accountsInfo`
- `personal_listAccounts`
- `personal_listGethAccounts`

Does the split on the Rust side and re-enables the use of personal_accountsInfo on the dapps side (used for mapping accounts to names)

### CODE REVIEW

**Comment by tomusdrw** [comment]
I'm not sure if any dapps are already relying on `personal_unlockAccount` or `personal_signAndSendTransaction` to be exposed.

For backward compatibility we could expose those methods, but slightly modified:
1. Instead of expecting a password to decrypt the key it would expect single-use password.
2. Such password could be generated in secure signer.
or
1. We can accept any password there
2. Convert it to standard Signing request

Just leaving it here if we ever consider that.

**Comment by jacogr** [comment]
Found a couple of subtle issues where the initial rush to remove all `personal_accountsinfo` didn't catch the corner cases. Since the JS side basically moves back to prior to personal-being-completely-locked, it will solve some nigglies in the dapps.

**Comment by jacogr** [comment]
@gavofyork As discussed, @tomusdrw also made the changes so safe is not only listAccounts & accountsInfo. Please review, would like to get this in and humming.

**Comment by rphmeier** [comment]
Core portion LGTM. `Personal` looks like it can be easily ported to `auto_args` now. The signer return values are still blocking the other personal APIs.

**Comment by rphmeier** [comment]
(would like a UI sign-off as well)

**Comment by jacogr** [comment]
UI was just a revert of the previous half-fix when it was removed. All dapps tested on this branch.

**Comment by jacogr** [comment]
@ngotchac Ping.

**Comment by ngotchac** [comment]
Looks good to me

**Pull request merged**
