### PR TITLE
Unify major syncing detection

### PR DESCRIPTION
**Pull request by keorn**
Improves #2639.
Tested on two nodes in various sync conditions (early, mid, import), it is reliable when repeatedly querying RPC. Still returns `false` for a few seconds of initial sync, but thats rather unavoidable.
Should also improve situations similar to the attack when lots of uncles were increasing queue size, possibly leading to "Syncing" console output.

Its not used for mission critical stuff so block delay can be adjusted later (4 behind now).

### CODE REVIEW

**Comment by tomusdrw** [comment]
RPC test is failing.

**Comment by arkpar** [comment]
This does not seem right to me. Block queue can still have a few thousand blocks to process after the `sync` modules completes a download. `eth_syncing` should return false only after the block queue has been cleared out.

**Comment by keorn** [comment]
In this case isn't it [`SyncState::Waiting`](https://github.com/ethcore/parity/blob/3ad8c4f2a2aaad8cad950edeb416d1d755946d5d/sync/src/chain.rs#L166)? `SyncState::Waiting` implies major sync here.

**Comment by arkpar** [comment]
No, the `sync` does not track the queue status after it is done downloading blocks. That's why there was a check for the queue status in the original code.

**Pull request merged**
