### PR TITLE
update hyper branch mio

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by jacogr** [comment]
Tried from a clone, then updated to the branch as requested in https://github.com/ethcore/parity/issues/1053

```
parity git:(hyper-update-2)$ cargo build --release
 Downloading docopt v0.6.80
 Downloading memchr v0.1.11
 Downloading num-bigint v0.1.32
 Downloading serde_codegen v0.7.2
 Downloading cookie v0.2.4
 Downloading num-rational v0.1.32
 Downloading env_logger v0.3.3
 Downloading bitflags v0.6.0
 Downloading quasi v0.9.0
 Downloading num-integer v0.1.32
 Downloading rotor v0.6.3
 Downloading rustc-serialize v0.3.19
 Downloading regex v0.1.68
 Downloading bincode v0.5.4
 Downloading num-iter v0.1.32
 Downloading quasi_codegen v0.9.0
 Downloading time v0.1.35
 Downloading thread-id v2.0.0
 Downloading kernel32-sys v0.2.2
 Downloading jsonrpc-core v2.0.2
 Downloading num-complex v0.1.32
 Downloading syntex v0.31.0
 Downloading url v0.5.9
 Downloading log v0.3.6
 Downloading rust-crypto v0.2.35
 Downloading nom v1.2.2
 Downloading chrono v0.2.22
 Downloading url v1.0.0
 Downloading xmltree v0.3.2
 Downloading gcc v0.3.28
 Downloading spmc v0.2.0
 Downloading nix v0.5.0
 Downloading aster v0.15.0
 Downloading idna v0.1.0
 Downloading syntex_syntax v0.31.0
 Downloading num-traits v0.1.32
 Downloading byteorder v0.5.1
 Downloading num v0.1.32
 Downloading uuid v0.2.1
 Downloading crossbeam v0.2.9
 Downloading libc v0.2.10
 Downloading void v1.0.2
 Downloading mio v0.5.1
 Downloading xml-rs v0.3.0
 Downloading thread_local v0.2.5
unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/jacogreeff/.multirust/toolchains/beta/cargo/registry/src/github.com-88ac128001ac3a9a/rpassword-0.2.2/Cargo.toml`

Caused by:
  could not parse input as TOML
/Users/jacogreeff/.multirust/toolchains/beta/cargo/registry/src/github.com-88ac128001ac3a9a/rpassword-0.2.2/Cargo.toml:13:9 expected a key but found an empty string
/Users/jacogreeff/.multirust/toolchains/beta/cargo/registry/src/github.com-88ac128001ac3a9a/rpassword-0.2.2/Cargo.toml:13:9-13:10 expected `.`, but found `'`
```

**Comment by NikVolf** [comment]
weird
can you please remove rpassword with
``` 
rm -rf ~/.multirust/toolchains/beta/cargo/registry/src/github.com-88ac128001ac3a9a/rpassword-0.2.2/
```

**Comment by jacogr** [comment]
^^^ I'm just updating my beta toolchain (it is set to stable as default) and will retry.

**Comment by jacogr** [comment]
@NikVolf Sorry, the compile took a bit longer than usual since I started with a fresh clone. (I was a bit behind master locally, so it would have taken a bit longer anyway)

However after it is all said and done (and after upgrading my beta to fix rpassword - not sure what caused that one), this branch does exactly what it says on the box. It upgrades hyper (the 0.9.3 branch checks out and compiles) and the full build runs to completion now on OS X. 

The resulting compiled parity binary works and syncs.

```
release git:(hyper-update-2)$ ./parity
Adding ver.lock
Executed 1 upgrade scripts - ok
2016-05-07 10:33:30 Starting Parity/v1.2.0-unstable-2e76def-20160507/x86_64-macos/rustc1.9.0-beta.2
2016-05-07 10:33:30 Configured for Frontier/Homestead using "Ethash" engine
2016-05-07 10:33:30 Public node URL: enode://1f64f15db9f842087c938c6b1bcc2719595e1bd7fa9fc1dae38a89f31fce14cc67e50aa6e3939106ac987174100edab6fc50900716b970782c56aea4e2012c5a@0.0.0.0:30303
2016-05-07 10:33:31 Using a conversion rate of Ξ1 = US$9.39 (25356253000 wei/gas)
[ #1399992 48ca…ae25 ]---[ 13 blk/s | 82 tx/s | 2346050 gas/s  //··· 1/3 peers, #1399992, 0+0 queued ···// mem: 0 bytes db, 592 KiB chain, 2 KiB queue, 38 KiB sync ]
```

**Comment by NikVolf** [comment]
nice, thanx for helping

**Pull request merged**
