### PR TITLE
make menus look like the rest of the UI

### PR DESCRIPTION
**Pull request by derhuerst**
This addresses #2351.

I dug through the guts of material-ui, which has a `paper.backgroundColor` option. I hope that this change doesn't break anything visually. I tried variations of black and dark grey and this is a mix I found acceptable.

The next step would be to clean up remaining overwrites of these styles.

### CODE REVIEW

**Comment by jacogr** [comment]
Pulled down and took a look -

1. Not convinced with the new sea-green buttons (toggle icons) & using it to show the selection in the menu. It is a new colour being introduced, doesn't quite fit.

2. The transparency is too much at 0.9, however at 0.95 it shows the same issues we have currently, i.e. no better for a fitting-in perspective.

Unless we want to spend time on doing what we did for the modal backgrounds, or have time to burn, I think we shoudl just put it on ice since this PR makes things slightly more out of place in some areas (sea-green) and has some un-intended visual impacts elsewhere (backgrounds).

**Comment by derhuerst** [comment]
> Not convinced with the new sea-green buttons (toggle icons) & using it to show the selection in the menu. It is a new colour being introduced, doesn't quite fit.

I disagree. afaik this change removes all the pink (which i think doesn't fit). [The Material UI dark theme uses dark cyan tones by default](https://github.com/callemall/material-ui/blob/62a1557/src/styles/baseThemes/darkBaseTheme.js#L14-L16), tried to get close to this with [`cyanA100`, `cyanA200` and `cyanA400`](http://www.material-ui.com/#/customization/colors).

> The transparency is too much at 0.9, however at 0.95 it shows the same issues we have currently, i.e. no better for a fitting-in perspective.

I agree that it is not optimal, but imho it's an improvement.

**Comment by derhuerst** [comment]
> […] has some un-intended visual impacts elsewhere (backgrounds).

I assume you mean the green background? Removed that in the latest commit.

In general, I'm neither in support of against of this change. You decide.

**Comment by gavofyork** [comment]
on ice until further progress is made

**Comment by jacogr** [comment]
Closing PR until we have resources to focus on it.

**Pull request closed without merging**
