### PR TITLE
TX queue gas limit config and allow local transactions over the gas limit

### PR DESCRIPTION
**Pull request by arkpar**
#2547

### CODE REVIEW

**Comment by tomusdrw** [comment]
Shouldn't we propagate limited number of transactions (for instance blockgas*2) in case of  `--tx-queue-gas off`?

**Comment by arkpar** [comment]
What about `--tx-queue-gas 100000000`? 
Also local transaction should be sent out regardless of the limit.
Better fix would be to track previously sent transactions for each peer. 
This is left for a future PR.

**Comment by rphmeier** [comment]
@arkpar We could track perviously-sent transactions for each peer (actually, it's considered Bad Form to send txs to the same peer more than once) but we have to be careful to limit the memory used while tracking this so the footprint of long-running nodes stays low.

**Comment by trapp** [comment]
If you do something like this please don't forget to whitelist the peers from the `--reserved_peers` list for those limits.

**Pull request merged**
