### PR TITLE
fetch known code from the database during restoration

### PR DESCRIPTION
**Pull request by rphmeier**
previously it kept all seen code in memory, leading to high memory usage by the end of state restoration.

Lowers memory usage by ~150MB when warp syncing.
Related to #3304

### CODE REVIEW

**Comment by gavofyork** [comment]
js-tests fail :-S

**Comment by gavofyork** [comment]
does a test hit this codepath?

**Comment by rphmeier** [comment]
Haven't touched any JS here. I think that the `snap_and_restore` test will hit this codepath but I can write another specialized one as well.

**Comment by rphmeier** [comment]
Ok, test added.

**Comment by rphmeier** [comment]
Think this one should be a B0-patch?

**Pull request merged**
