### PR TITLE
Fix flaky test

### PR DESCRIPTION
**Pull request by keorn**
and clean up chain specs.

### CODE REVIEW

**Comment by rphmeier** [comment]
What does the `rlp` member mean for a generic-family engine?

**Comment by keorn** [comment]
Its just the genesis block seal. So these just change the initial value of seal fields to 0.

**Comment by rphmeier** [comment]
interesting...why not use a JSON array and enforce the length to be equal to the length? seems a bit more flexible/tweakable than having to re-encode RLP to make changes

**Comment by keorn** [comment]
That's how it was.
I think it might be best to get rid of "fields" (redundant) and just have the RLP field which has to be a valid list (then it is compatible with whatever the seal generating function outputs, not requiring partial decoding). Also new `seal` type can be added if there is a new prominent `Engine`.

**Pull request merged**
