### PR TITLE
fixed #1180

### LINKED ISSUE #1180: eth_getTransactionReceipt should return receipt even if transaction is pending
todo:
- implement transactionReceipt for pending transaction

then...
- check if mist (or or foundation wallet) assumes that transactionReceipt == minedTransaction
- fix it, if it does

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by rphmeier** [comment]
#1180 also mentions that there might be an issue in Mist/Foundation wallet that needs fixing as well.

**Comment by debris** [comment]
ahh, yes. Checking it right now...

**Comment by gavofyork** [comment]
waiting for the answer...

**Comment by gavofyork** [comment]
*bump*

**Comment by gavofyork** [comment]
shame there's no tests....

**Pull request merged**
