### PR TITLE
Enable Panic=abort

### PR DESCRIPTION
**Pull request by arkpar**

### CODE REVIEW

**Comment by rphmeier** [comment]
perf gains/binary size difference?

**Comment by arkpar** [comment]
Binary is 2 megabytes smaller. Compile time 5% faster.

**Comment by rphmeier** [comment]
Sounds good. Hope it all works :)

**Comment by arkpar** [comment]
No, stack backtrace and panic message is still there.

**Comment by rphmeier** [comment]
relnotes for this one?

**Comment by arkpar** [comment]
Don't think it affects users in any way

**Pull request merged**
