### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jdetychey**
Added a fix to cargo failure when building from source

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 84a3197467e357a9fb9f0495610855db59b3abd0
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ethcore/parity

---
This message was auto-generated by https://gitcop.com

**Comment by jdetychey** [comment]
[clabot:check]

**Comment by jdetychey** [comment]
clabot:check

**Comment by jdetychey** [comment]
of course:
` ~/.cargo/bin//rustup default stable
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.15.1 (021bd294c 2017-02-08)
`
is better than nightly here

**Pull request closed without merging**
