### PR TITLE
util cleanup

### PR DESCRIPTION
**Pull request by debris**
- removed unused `util/squeeze.rs`
- removed unused `util/json_aid.rs`
- removed `util/json-tests` module. It was originally created by me as a replacement for ethereum / tests. 
  - there is just one test worth keeping there. it's `util/json-tests/json/trie/branching.json`
- few simplifications in `triehash.rs` iterators (7 lines added)

### CODE REVIEW

**Comment by gavofyork** [comment]
are these not the standard json tests that all trie implementations check against?

**Comment by debris** [comment]
> are these not the standard json tests that all trie implementations check against?

They are. I forgot about that. We can safely remove everything then :)

**Comment by gavofyork** [comment]
only if they're still checked from the standard tests. and i don't think they are.

**Comment by debris** [comment]
I've added `util/json-tests/json/trie/branching.json` test to `triedbmut.rs` in 321b16c

**Comment by gavofyork** [comment]
i'd prefer to keep the standard ethereum trie tests for completeness.

they are part of the cross-client consensus tests suite and i see no reason to remove.

**Comment by debris** [comment]
Removed files are not a part of cross-client consensus tests. We never used cross-client consensus tests for trie, cause these tests are placed in [6 json files](https://github.com/ethereum/tests/tree/develop/TrieTests) written in 3 different formats. Instead of using them directly I unified their format and placed them in `util/json-tests/json/trie` directory (it was back in December last year). This pr is moving these tests to the code.

We could add a module for parsing and running cross-client consensus tests, but imo it should not be a part of this pr

**Comment by gavofyork** [comment]
> This pr is moving these tests to the code.

only additional tests i see are the long random strings. where have those consensus-derived tests been moved to?

**Comment by debris** [comment]
All trie tests from ethereum/tests looks quite random. Anyway I've added a module, which is running all of them. [link](https://github.com/ethcore/parity/blob/d8b2844fd06e1e7e0aef74868428cac144468c09/ethcore/src/json_tests/trie.rs)

**Pull request merged**
