### PR TITLE
Signer method parameter decoding & destination info

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/ethcore/parity/issues/2208 & Closes https://github.com/ethcore/parity/issues/2280

https://youtu.be/b38dwc-1IYg

(Next PR: editing the transaction values & resubmissions)

### CODE REVIEW

**Comment by jacogr** [comment]
Marking WIP until https://github.com/ethcore/parity/pull/3642 is in and changes pulled-in.

**Comment by ngotchac** [comment]
This is a great improvement ! Especially removing that much unused code..

Small grumble : the very first column seems a bit big ; what about something like this :
```diff
diff --git a/js/src/views/Signer/components/TransactionMainDetails/TransactionMainDetails.css b/js/src/views/Signer/components/TransactionMainDetails/TransactionMainDetails.css
index 92ed968..3e077f3 100644
--- a/js/src/views/Signer/components/TransactionMainDetails/TransactionMainDetails.css
+++ b/js/src/views/Signer/components/TransactionMainDetails/TransactionMainDetails.css
@@ -19,6 +19,7 @@
 
 .transaction {
   flex: 1;
+  display: flex;
   overflow: auto;
 }
 
@@ -31,8 +32,8 @@
 }
 
 .from {
-  width: 40%;
   vertical-align: top;
+  padding: 0 3em;
 
   img {
     display: inline-block;
@@ -47,7 +48,7 @@
 }
 
 .method {
-  width: 60%;
+  flex: 1;
   vertical-align: top;
   line-height: 1em;
 }
```

**Comment by jacogr** [comment]
The issue with your approach is the following -

parity 2016-12-02 15-15-48

The current approach has all aligned in columns, no matter what the content is

**Comment by ngotchac** [comment]
Hmmm... Fair point

**Pull request merged**
