### PR TITLE
add update submodule step to "build from source"

### PR DESCRIPTION
**Pull request by king6cong**

### CODE REVIEW

**Comment by king6cong** [comment]
[clabot:check]

**Comment by arkpar** [comment]
This is not really required unless you want to run consensus tests. For most people that's just a waste of space and bandwidth.

**Comment by rphmeier** [comment]
It's also required for some RPC tests AFAIK. Maybe those files are wrongly included in non-test mode? I haven't heard of anyone encountering this issue before.

**Comment by 5chdn** [comment]
Closing as I can not understand the motivation behind this PR. The submodules are only required to run tests, and this is well documented in the Wiki. Usually, you wont need the submodules if you build Parity from source.

@king6cong if there is a case where you require the submodules for anything else than running tests, please let us know.

**Pull request closed without merging**
