### PR TITLE
checking transaction queue for pending transaction

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by NikVolf** [comment]
#836

**Comment by gavofyork** [comment]
would be nice to have a test for it...

**Comment by NikVolf** [comment]
@gavofyork 
yep, though there is no any logic here, and transaction_queue and miner transaction import are tested separately

**Comment by gavofyork** [comment]
test for `transaction_by_hash`?

**Comment by NikVolf** [comment]
yeah, didn't notice there was no test for it before

**Pull request merged**
