### PR TITLE
shapeshift Promise API library

### PR DESCRIPTION
**Pull request by jacogr**
Add a ShapeShift Promise-based API library for the upcoming fund integration into the UI. (Same location as the etherscan item)

### CODE REVIEW

**Comment by derhuerst** [comment]
Why don't we use [`chovy/shapeshift`](https://github.com/chovy/shapeshift#usage) or [`ExodusMovement/shapeshift.io`](https://github.com/ExodusMovement/shapeshift.io#methods)?

**Comment by jacogr** [comment]
The reality is that this code actually precedes the existence of both those. In this case I prefer a home-grown solution 

- don't need all the endpoints for our use-case
- one less external dep that we need to pull in (same deps as our other stuff)

As for specifics to those libraries -

- chovy - doesn't support API keys (affiliate), nor does it actually cater for the CORS endpoint, does have Promises, which is a positive
- Exodus - not Promised-based, will need to wrap,  ApiKey not available for shift (interesting can get the txlist for it), does cater for CORS, which is a positive

**Comment by derhuerst** [comment]
> one less external dep that we need to pull in (same deps as our other stuff)

But more code to maintain & more general "mental overload" because of a huge project.

> Exodus - not Promised-based, will need to wrap, ApiKey not available for shift (interesting can get the txlist for it), does cater for CORS, which is a positive

I think a PR that builds on top of ExodusMovement/shapeshift.io#3 would be nice here. Let's contribute back & not lock everything into one giant repo. We'd be able to comfortably use the lib if someone else had bothered to contribute.

**Comment by jacogr** [comment]
Rather -

1. I know this library works, build ShapeShift integration on top of it already, ready to import from a UI perspective
2. I'd rather spend the 3 hours importing (UI-wise) what I know is working and tested on the live network than working on another repo fixing another lib, waiting for the PR to get merged at some point and then re-developing what is there from a UI perspective

Quite happy to re-visit at some point if need be, but at this point I see no gains whatsoever, just a long draw-out process for 3 API calls.

**Pull request merged**
